export const WILLOW_VALE = {
    id: "willowVale",
    name: "Vrbové údolí",
    subtitle: "Prolog — Noc bez ozvěny",
    skyTop: "#596f86",
    skyBottom: "#a3926c",
    floorNear: "#3b482a",
    floorFar: "#1e2618",
    fog: "#606b59",
    music: [110, 146.83, 164.81, 220, 196, 164.81],
    start: { x: 3.5, y: 19.5, direction: -Math.PI / 2 },
    map: [
      "111111111111111111111111",
      "100000000000000000000001",
      "100000000000000000000001",
      "100033333000000333330001",
      "100030003000000300030001",
      "100030003000000300030001",
      "100033233000000333330001",
      "100000000000000000000001",
      "100000000111100000000001",
      "100000000100100000000001",
      "100000000100100000000001",
      "100000000122100000000001",
      "100000000000000000000001",
      "100011111000000111110001",
      "100010001000000100010001",
      "100010001000000100010001",
      "100012221000000122210001",
      "100000000000000000000001",
      "100000000000000000000001",
      "100000000000000000000001",
      "100000000000000000000001",
      "100000000000000000000001",
      "100000000000000000000001",
      "111111111111111111111111"
    ],
    entities: [
      {
        id: "elira",
        kind: "npc",
        name: "Strážkyně Elira",
        x: 18.5,
        y: 10.5,
        solid: true,
        dialogueId: "elira",
        interaction: { type: "dialogue", prompt: "Promluvit s Elirou" },
      },
      {
        id: "tomar",
        kind: "npc",
        name: "Kupec Tomar",
        x: 5.5,
        y: 19.5,
        solid: true,
        dialogueId: "tomar",
        interaction: { type: "dialogue", prompt: "Promluvit s Tomarem" },
      },
      {
        id: "mira",
        kind: "npc",
        name: "Bylinkářka Mira",
        x: 17.5,
        y: 19.5,
        solid: true,
        dialogueId: "mira",
        interaction: { type: "dialogue", prompt: "Promluvit s Mirou" },
      },
      {
        id: "silver-marker",
        kind: "obelisk",
        name: "Rozbitý stříbrný mezník",
        x: 12.5,
        y: 7.5,
        solid: true,
        interaction: {
          type: "inspect",
          prompt: "Prozkoumat mezník",
          title: "Rozbitý stříbrný mezník",
          text: "Kámen je rozštípnutý zevnitř. Ve stříbrných žilách nezůstala síla, pouze dokonale pravidelné kruhy připomínající otisk zvukové vlny. Na severovýchod vede slabá stopa modrého prachu.",
          event: "inspect",
          target: "silver-marker",
        },
      },
      {
        id: "silver-fragment",
        kind: "fragment",
        name: "Krystalický střep",
        x: 20.5,
        y: 4.5,
        solid: false,
        visibleWhen: [{ type: "questStage", questId: "silverEcho", stageIndex: 1 }],
        interaction: {
          type: "collect",
          prompt: "Zabalit krystalický střep",
          itemId: "silver-fragment",
          itemName: "Krystalický střep",
          event: "collect",
          target: "silver-fragment",
          text: "Lyra zabalila střep do kusu plátna. Uvnitř krystalu se opakuje tón, který zní téměř jako šeptané slovo.",
        },
      },
      {
        id: "lost-satchel",
        kind: "satchel",
        name: "Tomarova brašna",
        x: 3.5,
        y: 12.5,
        solid: false,
        visibleWhen: [{ type: "questStage", questId: "lostSatchel", stageIndex: 0 }],
        interaction: {
          type: "collect",
          prompt: "Zvednout koženou brašnu",
          itemId: "lost-satchel",
          itemName: "Tomarova brašna",
          event: "collect",
          target: "lost-satchel",
          text: "Mosazná spona ve tvaru lišky je poškrábaná, ale tři zapečetěné dopisy uvnitř zůstaly suché.",
        },
      },
      ...[
        ["moonleaf-a", 7.5, 7.5],
        ["moonleaf-b", 18.5, 7.5],
        ["moonleaf-c", 20.5, 12.5],
      ].map(([id, x, y]) => ({
        id,
        kind: "herb",
        name: "Měsíčník",
        x,
        y,
        solid: false,
        visibleWhen: [{ type: "questStage", questId: "moonleafTonic", stageIndex: 0 }],
        interaction: {
          type: "collect",
          prompt: "Nasbírat měsíčník",
          itemId: "moonleaf",
          itemName: "Měsíčník",
          event: "collect",
          target: "moonleaf",
          text: "Modravé listy jsou chladné a jejich bílé žilky slabě světélkují.",
        },
      })),
      {
        id: "road-sign",
        kind: "sign",
        name: "Starý směrovník",
        x: 6.5,
        y: 18.5,
        solid: false,
        interaction: {
          type: "inspect",
          prompt: "Přečíst směrovník",
          title: "Starý směrovník",
          text: "SEVER — Stříbrná brána. VÝCHOD — Klášter tichého zvonu. ZÁPAD — Hlubinné doly. Pod názvy někdo čerstvě vyryl větu: ‚Kámen zapomene, když mu dost dlouho lžete.‘",
          flag: "lore:signWarning",
        },
      },
      {
        id: "weathered-tablet",
        kind: "obelisk",
        name: "Zvětralá pamětní deska",
        x: 10.5,
        y: 18.5,
        solid: true,
        interaction: {
          type: "inspect",
          prompt: "Přečíst pamětní desku",
          title: "Pamětní deska",
          text: "‚Těm, kteří drželi bránu během Popelavé noci. Jejich jména uchová kámen, dokud bude stříbro zpívat.‘ Poslední řádek byl úmyslně odsekán.",
          flag: "lore:ashNightMemorial",
        },
      },
      {
        id: "tomar-stall",
        kind: "stall",
        name: "Tomarův polní obchod",
        x: 6.5,
        y: 20.5,
        solid: true,
        interaction: { type: "shop", vendorId: "tomar", prompt: "Obchodovat s Tomarem" },
      },
      {
        id: "mira-stall",
        kind: "stall",
        name: "Miřin bylinkářský stůl",
        x: 16.5,
        y: 20.5,
        solid: true,
        interaction: { type: "shop", vendorId: "mira", prompt: "Prohlédnout Miřinu nabídku" },
      },
      {
        id: "road-cache",
        kind: "chest",
        name: "Opuštěná cestovní truhla",
        x: 4.5,
        y: 9.5,
        solid: true,
        interaction: { type: "loot", lootTable: "roadCache", prompt: "Otevřít cestovní truhlu" },
      },
      {
        id: "watch-armory-cache",
        kind: "chest",
        name: "Zapečetěná schránka hlídky",
        x: 20.5,
        y: 14.5,
        solid: true,
        interaction: { type: "loot", lootTable: "watchArmory", prompt: "Otevřít schránku hlídky" },
      },
      {
        id: "herbal-crate",
        kind: "crate",
        name: "Zapomenutá bedna bylin",
        x: 18.5,
        y: 17.5,
        solid: true,
        interaction: { type: "loot", lootTable: "herbalCrate", prompt: "Prohledat bednu bylin" },
      },
      {
        id: "echo-hound-west",
        kind: "enemyHound",
        enemyId: "echoHound",
        name: "Ozvěnový honič",
        x: 6.5,
        y: 8.5,
        homeX: 6.5,
        homeY: 8.5,
        solid: true,
        groupId: "north-hunt",
      },
      {
        id: "echo-hound-packmate",
        kind: "enemyHound",
        enemyId: "echoHound",
        name: "Ozvěnový honič",
        x: 8.5,
        y: 8.5,
        homeX: 8.5,
        homeY: 8.5,
        solid: true,
        groupId: "north-hunt",
      },
      {
        id: "echo-hound-east",
        kind: "enemyHound",
        enemyId: "echoHound",
        name: "Ozvěnový honič",
        x: 17.5,
        y: 8.5,
        homeX: 17.5,
        homeY: 8.5,
        solid: true,
        groupId: "north-hunt",
      },
      {
        id: "mire-crawler-east",
        kind: "enemyCrawler",
        enemyId: "mireCrawler",
        name: "Bahenní lezoun",
        x: 20.5,
        y: 9.5,
        homeX: 20.5,
        homeY: 9.5,
        solid: true,
        groupId: "north-hunt",
      },
      {
        id: "ash-raider-south",
        kind: "enemyRaider",
        enemyId: "ashRaider",
        name: "Popelavý nájezdník",
        x: 12.5,
        y: 21.5,
        homeX: 12.5,
        homeY: 21.5,
        solid: true,
        groupId: "southern-raiders",
      },
      {
        id: "hollow-sentinel-north",
        kind: "enemySentinel",
        enemyId: "hollowSentinel",
        name: "Dutý strážce",
        x: 12.5,
        y: 3.5,
        homeX: 12.5,
        homeY: 3.5,
        solid: true,
        groupId: "warden-court",
      },
      {
        id: "hollow-sentinel-warden",
        kind: "enemySentinel",
        enemyId: "hollowSentinel",
        name: "Dutý strážce nádvoří",
        x: 21.5,
        y: 3.5,
        homeX: 21.5,
        homeY: 3.5,
        solid: true,
        groupId: "warden-court",
      },
      {
        id: "echo-warden",
        kind: "enemyWarden",
        enemyId: "echoWarden",
        name: "Dozorce zlomené ozvěny",
        x: 20.5,
        y: 2.5,
        homeX: 20.5,
        homeY: 2.5,
        solid: true,
        groupId: "warden-court",
      },
      {
        id: "willow-east-road",
        kind: "portal",
        name: "Cesta ke Stříbrné bráně",
        x: 22.5,
        y: 12.5,
        solid: false,
        render: false,
        interaction: {
          type: "transition",
          prompt: "Vyrazit k horské cestě",
          targetZone: "silverPass",
          targetSpawn: "fromVale",
          requiresItem: "eliras-seal",
          lockedText: "Cestu uzavírá stříbrná závora. Eliřina pečeť by ji měla odemknout.",
        },
      },
      { id: "torch-a", kind: "torch", name: "Pochodeň", x: 9.5, y: 12.5, solid: false },
      { id: "torch-b", kind: "torch", name: "Pochodeň", x: 14.5, y: 12.5, solid: false },
    ],
};
